name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer

      - name: Run Slither
        run: |
          slither . --exclude-dependencies --exclude-informational

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Echidna
        run: |
          docker pull ghcr.io/crytic/echidna
          for file in src/vulnerabilities/*.sol; do
            docker run -v $PWD:/code ghcr.io/crytic/echidna /code/$file
          done

      - name: Run Custom Security Checks
        run: |
          forge script script/security-check.s.sol

      - name: Generate Security Report
        if: always()
        run: |
          echo "# Security Analysis Report" > security-report.md
          echo "## Slither Results" >> security-report.md
          slither . --print human-summary >> security-report.md
          echo "## Test Coverage" >> security-report.md
          forge coverage --report lcov >> security-report.md

      - name: Upload Security Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security-report.md 